minecraft_version=1.21.11
minecraft_version_range=[1.21.11,1.22)
forge_version=21.11.0-beta
forge_version_range=[21.11.0-beta,)
fabric_version=0.18.2
fabric_api_version=0.139.4+1.21.11
loader_version_range=[1,)
mod_license=LGPL-3.0-only
resource_pack_max_format=75
resource_pack_min_format=50
data_pack_format=94
modProperties=[]
modDependencies=[]
modMixins=[]
modSides=[ "Client", "Server" ]

# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx5G
org.gradle.daemon=false
