minecraft_version=26.2
minecraft_version_range=[26.2,)
forge_version=26.2.0.53-beta
forge_version_range=[26.2.0.6-beta,)
fabric_version=0.19.3
fabric_api_version=0.156.0+26.2
loader_version_range=[1,)
mod_license=LGPL-3.0-only
resource_pack_max_format=88
resource_pack_min_format=82
data_pack_format=107
modProperties=[]
modDependencies=[]
modMixins=[]
modSides=[ "Client", "Server" ]

# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx5G
org.gradle.daemon=false
